<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>JavaScript 错误 - Throw、Try 和 Catch</title>
	</head>
	<body>
		<h1>My First JavaScript</h1>
		<p>Please input a number between 5 and 10:</p>
		<input id="demo" type="text" required="true">
		<button type="button" onclick="myFunction()">Test Input</button>
		<p id="mess"></p>
	</body>
	<script>
		//try语句测试代码块的错误
		//catch语句处理错误
		//throw语句创建自定义错误
		//这就是一种调试代码的错误
		//在控制台里就可以看到哪里报错了
		
		function myFunction(){
			try
			  {
			  var x=document.getElementById("demo").value;
			  if(x=="")    throw "empty";
			  if(isNaN(x)) throw "not a number";
			  if(x>10)     throw "too high";
			  if(x<5)      throw "too low";
			  }
			catch(err)
			  {
			  var y=document.getElementById("mess");
			  y.innerHTML="Error: " + err + ".";
			  }
			}
	</script>
</html>
